INSERT INTO KUNSTGALERIE (ID, ORT, EXPONATE) VALUES ('ka', 'Karlsruhe', 2);
INSERT INTO GEMAELDE (KUNSTGALERIE_ID, KUENSTLER, JAHR, NAME, PREIS) VALUES ('ka', 'Vincent Van Gogh', 1743, 'Die Schattenwiese', 1000000);
INSERT INTO GEMAELDE (KUNSTGALERIE_ID, KUENSTLER, JAHR, NAME, PREIS) VALUES ('ka', 'Leonardo Da Vinci', 1659, 'Der Schrecken', 23999);

INSERT INTO KUNSTGALERIE (ID, ORT, EXPONATE) VALUES ('fr', 'Frankfurt', 1);
INSERT INTO GEMAELDE (KUNSTGALERIE_ID, KUENSTLER, JAHR, NAME, PREIS) VALUES ('fr', 'Renate von Überlingen', 2019, 'Das monumentale Monument', 10);

