INSERT INTO KUNSTGALERIE (ID, ORT, EXPONATE) VALUES (1, 'Karlsruhe', 2);
INSERT INTO GEMAELDE (KUNSTGALERIE_ID, KUENSTLER, JAHR, NAME, PREIS) VALUES (1, 'Vincent Van Gogh', 1743, 'Die Schattenwiese', 1000000);
INSERT INTO GEMAELDE (KUNSTGALERIE_ID, KUENSTLER, JAHR, NAME, PREIS) VALUES (1, 'Leonardo Da Vinci', 1659, 'Der Schrecken', 23999);

INSERT INTO KUNSTGALERIE (ID, ORT, EXPONATE) VALUES (2, 'Frankfurt', 1);
INSERT INTO GEMAELDE (KUNSTGALERIE_ID, KUENSTLER, JAHR, NAME, PREIS) VALUES (2, 'Renate von Überlingen', 2019, 'Das monumentale Monument', 10);

